using System;
using System.Collections.Generic;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ProjectEuler
{
    /// <summary>
    /// Even Fibonacci numbers
    /// 
    /// Problem 2
    /// 
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
    /// 
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// 
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    [TestClass]
    public class Problem2
    {
        [TestMethod]
        public void Solution()
        {
            const int MAX = 5000000;

            IList<int> fibonacci = new List<int> { 1, 2 }; //starting number is 1 & 2
            long sum = 2; //first even sum
            while(sum < MAX)
            {
                var next = fibonacci[fibonacci.Count - 2] + fibonacci[fibonacci.Count - 1];
                fibonacci.Add(next);

                //Even only
                if (next % 2 == 0)
                {
                    if (sum + next > MAX)
                    {
                        break;
                    }
                    sum += next;
                }
                
            }

            sum.Should().Be(4613732);
        }
    }
}
